<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExternalBankSeeder extends Seeder
{
    public function run(): void
    {
        $banks = [
            ['bank_code' => '002', 'bank_name' => 'Bank BRI', 'is_active' => true],
            ['bank_code' => '008', 'bank_name' => 'Bank Mandiri', 'is_active' => true],
            ['bank_code' => '009', 'bank_name' => 'Bank BNI', 'is_active' => true],
            ['bank_code' => '013', 'bank_name' => 'Bank Permata', 'is_active' => true],
            ['bank_code' => '014', 'bank_name' => 'Bank BCA', 'is_active' => true],
            ['bank_code' => '016', 'bank_name' => 'Bank Maybank', 'is_active' => true],
            ['bank_code' => '019', 'bank_name' => 'Bank Panin', 'is_active' => true],
            ['bank_code' => '022', 'bank_name' => 'Bank CIMB Niaga', 'is_active' => true],
            ['bank_code' => '023', 'bank_name' => 'Bank UOB Indonesia', 'is_active' => true],
            ['bank_code' => '028', 'bank_name' => 'Bank OCBC NISP', 'is_active' => true],
            ['bank_code' => '031', 'bank_name' => 'Bank Citibank', 'is_active' => true],
            ['bank_code' => '037', 'bank_name' => 'Bank Artha Graha', 'is_active' => true],
            ['bank_code' => '041', 'bank_name' => 'Bank HSBC Indonesia', 'is_active' => true],
            ['bank_code' => '046', 'bank_name' => 'Bank DBS Indonesia', 'is_active' => true],
            ['bank_code' => '050', 'bank_name' => 'Bank Standard Chartered', 'is_active' => true],
            ['bank_code' => '054', 'bank_name' => 'Bank Capital Indonesia', 'is_active' => true],
            ['bank_code' => '061', 'bank_name' => 'Bank ANZ Indonesia', 'is_active' => true],
            ['bank_code' => '069', 'bank_name' => 'Bank Mestika Dharma', 'is_active' => true],
            ['bank_code' => '087', 'bank_name' => 'Bank Ekonomi Raharja', 'is_active' => true],
            ['bank_code' => '089', 'bank_name' => 'Bank Rakyat Indonesia Agroniaga', 'is_active' => true],
            ['bank_code' => '097', 'bank_name' => 'Bank Jtrust Indonesia', 'is_active' => true],
            ['bank_code' => '110', 'bank_name' => 'Bank Jabar Banten (BJB)', 'is_active' => true],
            ['bank_code' => '111', 'bank_name' => 'Bank DKI', 'is_active' => true],
            ['bank_code' => '112', 'bank_name' => 'Bank BPD DIY', 'is_active' => true],
            ['bank_code' => '113', 'bank_name' => 'Bank Jateng', 'is_active' => true],
            ['bank_code' => '114', 'bank_name' => 'Bank Jatim', 'is_active' => true],
            ['bank_code' => '115', 'bank_name' => 'Bank Jambi', 'is_active' => true],
            ['bank_code' => '116', 'bank_name' => 'Bank Aceh Syariah', 'is_active' => true],
            ['bank_code' => '117', 'bank_name' => 'Bank Sumut', 'is_active' => true],
            ['bank_code' => '118', 'bank_name' => 'Bank Nagari', 'is_active' => true],
            ['bank_code' => '119', 'bank_name' => 'Bank Riau Kepri', 'is_active' => true],
            ['bank_code' => '120', 'bank_name' => 'Bank Sumsel Babel', 'is_active' => true],
            ['bank_code' => '121', 'bank_name' => 'Bank Lampung', 'is_active' => true],
            ['bank_code' => '122', 'bank_name' => 'Bank Kalsel', 'is_active' => true],
            ['bank_code' => '123', 'bank_name' => 'Bank Kalbar', 'is_active' => true],
            ['bank_code' => '124', 'bank_name' => 'Bank Kaltimtara', 'is_active' => true],
            ['bank_code' => '125', 'bank_name' => 'Bank Kalteng', 'is_active' => true],
            ['bank_code' => '126', 'bank_name' => 'Bank Sulselbar', 'is_active' => true],
            ['bank_code' => '127', 'bank_name' => 'Bank Sulutgo', 'is_active' => true],
            ['bank_code' => '128', 'bank_name' => 'Bank NTB Syariah', 'is_active' => true],
            ['bank_code' => '129', 'bank_name' => 'Bank BPD Bali', 'is_active' => true],
            ['bank_code' => '130', 'bank_name' => 'Bank NTT', 'is_active' => true],
            ['bank_code' => '131', 'bank_name' => 'Bank Maluku Malut', 'is_active' => true],
            ['bank_code' => '132', 'bank_name' => 'Bank Papua', 'is_active' => true],
            ['bank_code' => '133', 'bank_name' => 'Bank Bengkulu', 'is_active' => true],
            ['bank_code' => '134', 'bank_name' => 'Bank Sulteng', 'is_active' => true],
            ['bank_code' => '135', 'bank_name' => 'Bank Sultra', 'is_active' => true],
            ['bank_code' => '145', 'bank_name' => 'Bank Nusantara Parahyangan', 'is_active' => true],
            ['bank_code' => '146', 'bank_name' => 'Bank Muamalat', 'is_active' => true],
            ['bank_code' => '147', 'bank_name' => 'Bank Mestika', 'is_active' => true],
            ['bank_code' => '151', 'bank_name' => 'Bank Sinarmas', 'is_active' => true],
            ['bank_code' => '153', 'bank_name' => 'Bank Maspion', 'is_active' => true],
            ['bank_code' => '157', 'bank_name' => 'Bank Mitra Niaga', 'is_active' => true],
            ['bank_code' => '161', 'bank_name' => 'Bank Ganesha', 'is_active' => true],
            ['bank_code' => '164', 'bank_name' => 'Bank ICBC Indonesia', 'is_active' => true],
            ['bank_code' => '167', 'bank_name' => 'Bank QNB Indonesia', 'is_active' => true],
            ['bank_code' => '200', 'bank_name' => 'Bank BTN', 'is_active' => true],
            ['bank_code' => '213', 'bank_name' => 'Bank BTPN', 'is_active' => true],
            ['bank_code' => '405', 'bank_name' => 'Bank Syariah Indonesia (BSI)', 'is_active' => true],
            ['bank_code' => '422', 'bank_name' => 'Bank BRI Syariah', 'is_active' => true],
            ['bank_code' => '425', 'bank_name' => 'Bank Jabar Banten Syariah', 'is_active' => true],
            ['bank_code' => '426', 'bank_name' => 'Bank Mega', 'is_active' => true],
            ['bank_code' => '427', 'bank_name' => 'Bank BNI Syariah', 'is_active' => true],
            ['bank_code' => '441', 'bank_name' => 'Bank Bukopin', 'is_active' => true],
            ['bank_code' => '451', 'bank_name' => 'Bank Syariah Mandiri', 'is_active' => true],
            ['bank_code' => '484', 'bank_name' => 'Bank KEB Hana Indonesia', 'is_active' => true],
            ['bank_code' => '485', 'bank_name' => 'Bank MNC Internasional', 'is_active' => true],
            ['bank_code' => '490', 'bank_name' => 'Bank Yudha Bhakti', 'is_active' => true],
            ['bank_code' => '491', 'bank_name' => 'Bank Mitraniaga', 'is_active' => true],
            ['bank_code' => '494', 'bank_name' => 'Bank Rakyat Indonesia Agroniaga', 'is_active' => true],
            ['bank_code' => '498', 'bank_name' => 'Bank SBI Indonesia', 'is_active' => true],
            ['bank_code' => '501', 'bank_name' => 'Bank Royal Indonesia', 'is_active' => true],
            ['bank_code' => '503', 'bank_name' => 'Bank National Nobu', 'is_active' => true],
            ['bank_code' => '506', 'bank_name' => 'Bank Mega Syariah', 'is_active' => true],
            ['bank_code' => '513', 'bank_name' => 'Bank Ina Perdana', 'is_active' => true],
            ['bank_code' => '517', 'bank_name' => 'Bank Panin Dubai Syariah', 'is_active' => true],
            ['bank_code' => '520', 'bank_name' => 'Bank Prima Master', 'is_active' => true],
            ['bank_code' => '521', 'bank_name' => 'Bank Persyarikatan Indonesia', 'is_active' => true],
            ['bank_code' => '523', 'bank_name' => 'Bank Sahabat Sampoerna', 'is_active' => true],
            ['bank_code' => '526', 'bank_name' => 'Bank Dinar Indonesia', 'is_active' => true],
            ['bank_code' => '531', 'bank_name' => 'Bank Anglomas Internasional', 'is_active' => true],
            ['bank_code' => '535', 'bank_name' => 'Bank Kesejahteraan Ekonomi', 'is_active' => true],
            ['bank_code' => '536', 'bank_name' => 'Bank BCA Syariah', 'is_active' => true],
            ['bank_code' => '542', 'bank_name' => 'Bank Artos Indonesia', 'is_active' => true],
            ['bank_code' => '547', 'bank_name' => 'Bank Sahabat Purba Danarta', 'is_active' => true],
            ['bank_code' => '548', 'bank_name' => 'Bank Multiarta Sentosa', 'is_active' => true],
            ['bank_code' => '553', 'bank_name' => 'Bank Mayora Indonesia', 'is_active' => true],
            ['bank_code' => '555', 'bank_name' => 'Bank Index Selindo', 'is_active' => true],
            ['bank_code' => '558', 'bank_name' => 'Bank Eksekutif Internasional', 'is_active' => true],
            ['bank_code' => '559', 'bank_name' => 'Centratama Nasional Bank', 'is_active' => true],
            ['bank_code' => '562', 'bank_name' => 'Bank Fama Internasional', 'is_active' => true],
            ['bank_code' => '564', 'bank_name' => 'Bank Mandiri Taspen', 'is_active' => true],
            ['bank_code' => '566', 'bank_name' => 'Bank Victoria Internasional', 'is_active' => true],
            ['bank_code' => '567', 'bank_name' => 'Bank Harda Internasional', 'is_active' => true],
            ['bank_code' => '945', 'bank_name' => 'Bank Agris', 'is_active' => true],
            ['bank_code' => '947', 'bank_name' => 'Bank Mayapada', 'is_active' => true],
            ['bank_code' => '949', 'bank_name' => 'Bank Chinatrust Indonesia', 'is_active' => true],
            ['bank_code' => '950', 'bank_name' => 'Bank Commonwealth', 'is_active' => true],
        ];

        foreach ($banks as $bank) {
            DB::table('external_banks')->insert(array_merge($bank, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
